CRATE_NAME := gb_rs

SRCDIR := src
DSTDIR := build

CRATE_FLAGS := --crate-name $(CRATE_NAME) --edition=2024 --crate-type cdylib -L crate=$(DSTDIR)
# CODEGEN_FLAGS := -C opt-level=z -C panic=abort -C codegen-units=1 -C lto=true
CODEGEN_FLAGS := -C opt-level=z -C panic=abort -C lto=true

RUSTC_TARGET := --target wasm32-unknown-unknown

RUSTC_FLAGS := $(CRATE_FLAGS) $(CODEGEN_FLAGS) $(RUSTC_TARGET)


WASM_OBJ := $(DSTDIR)/$(CRATE_NAME).wasm
# TODO(yhr0x43): architecture dependent proc_macro artifact
PROC_MACRO_OBJ := $(DSTDIR)/libmy_proc_macro.so

.PHONY: all clean
all: $(DSTDIR) $(PROC_MACRO_OBJ) $(WASM_OBJ) $(DSTDIR)/$(CRATE_NAME).wat
$(WASM_OBJ): $(PROC_MACRO_OBJ) Makefile

clean:
	$(RM) build/*

# generated by rustc with --emit=dep-info option
RUSTC_DEPINFO := $(DSTDIR)/$(CRATE_NAME).d
ifneq ("$(wildcard $(RUSTC_DEPINFO))","")
    include $(RUSTC_DEPINFO)
endif

$(PROC_MACRO_OBJ): $(SRCDIR)/my_proc_macro.rs
	rustc $^ --out-dir $(DSTDIR)

$(DSTDIR):
	mkdir $(DSTDIR)

$(WASM_OBJ):
	rustc $(RUSTC_FLAGS) --emit=dep-info,link,mir,llvm-ir --out-dir $(DSTDIR) $(SRCDIR)/lib.rs

%.wat: %.wasm
	wasm2wat $^ -o $@
