CRATE_NAME := gb_rs

SRCDIR := src
DSTDIR := build

CRATE_FLAGS := --crate-name $(CRATE_NAME) --edition=2024 --crate-type cdylib
CODEGEN_FLAGS := --emit=dep-info,link,mir -C embed-bitcode=no --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())'
RELEASE_FLAGS := -C opt-level=s -C strip=debuginfo
DEBUG_FLAGS := -C opt-level=s -C debuginfo=2

RUSTC_TARGET := --target wasm32-unknown-unknown
#RUSTC_TARGET := --target wasm32v1-none

RUSTC_FLAGS := $(CRATE_FLAGS) $(CODEGEN_FLAGS) $(RUSTC_TARGET)

ifdef RELEASE
    RUSTC_FLAGS += $(RELEASE_FLAGS)
else
    RUSTC_FLAGS += $(DEBUG_FLAGS)
endif

WASM_OBJ := $(DSTDIR)/$(CRATE_NAME).wasm
# TODO(yhr0x43): architecture dependent proc_macro artifact
PROC_MACRO_OBJ := $(DSTDIR)/libmy_proc_macro.so

.PHONY: all
all: $(DSTDIR) $(PROC_MACRO_OBJ) $(WASM_OBJ)
$(WASM_OBJ): $(PROC_MACRO_OBJ) Makefile

# generated by rustc with --emit=dep-info option
RUSTC_DEPINFO := $(DSTDIR)/$(CRATE_NAME).d
ifneq ("$(wildcard $(RUSTC_DEPINFO))","")
    include $(RUSTC_DEPINFO)
endif

$(PROC_MACRO_OBJ): $(SRCDIR)/my_proc_macro.rs
	rustc $^ --out-dir $(DSTDIR)

$(DSTDIR):
	mkdir $(DSTDIR)

$(WASM_OBJ):
	rustc $(RUSTC_FLAGS) -L crate=build --out-dir $(DSTDIR) $(SRCDIR)/lib.rs
