CRATE_NAME := gb_rs

SRCDIR := src
DSTDIR := build

CRATE_FLAGS := --crate-name $(CRATE_NAME) --edition=2024 --crate-type cdylib -L crate=$(DSTDIR)
CODEGEN_FLAGS := -C opt-level=z -C panic=abort

RUSTC_TARGET := --target wasm32-unknown-unknown
#RUSTC_TARGET := --target wasm32v1-none

RUSTC_FLAGS := $(CRATE_FLAGS) $(CODEGEN_FLAGS) $(RUSTC_TARGET)


WASM_OBJ := $(DSTDIR)/$(CRATE_NAME).wasm
# TODO(yhr0x43): architecture dependent proc_macro artifact
PROC_MACRO_OBJ := $(DSTDIR)/libmy_proc_macro.so

.PHONY: all
all: $(DSTDIR) $(PROC_MACRO_OBJ) $(WASM_OBJ)
$(WASM_OBJ): $(PROC_MACRO_OBJ) Makefile

# generated by rustc with --emit=dep-info option
RUSTC_DEPINFO := $(DSTDIR)/$(CRATE_NAME).d
ifneq ("$(wildcard $(RUSTC_DEPINFO))","")
    include $(RUSTC_DEPINFO)
endif

$(RUSTC_DEPINFO):
	rustc $(RUSTC_FLAGS) --emit=dep-info --out-dir $(DSTDIR) $(SRCDIR)/lib.rs

$(PROC_MACRO_OBJ): $(SRCDIR)/my_proc_macro.rs
	rustc $^ --out-dir $(DSTDIR)

$(DSTDIR):
	mkdir $(DSTDIR)

$(WASM_OBJ):
	rustc $(RUSTC_FLAGS) --emit=link --out-dir $(DSTDIR) $(SRCDIR)/lib.rs
